language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script:
  - python -m irradpy.downloader.remote.socket --help
